package entity;
// Generated 16-09-2013 11:11:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Arrangement generated by hbm2java
 */
public class Arrangement  implements java.io.Serializable {


     private int arrangementId;
     private String navn;
     private String beskrivelse;
     private String dato;
     private Set tilmeldings = new HashSet(0);

    public Arrangement() {
    }

	
    public Arrangement(int arrangementId) {
        this.arrangementId = arrangementId;
    }
    public Arrangement(int arrangementId, String navn, String beskrivelse, String dato, Set tilmeldings) {
       this.arrangementId = arrangementId;
       this.navn = navn;
       this.beskrivelse = beskrivelse;
       this.dato = dato;
       this.tilmeldings = tilmeldings;
    }
    public Arrangement(int arrangementId, String navn, String beskrivelse, String dato) {
       this.arrangementId = arrangementId;
       this.navn = navn;
       this.beskrivelse = beskrivelse;
       this.dato = dato;
    }
   
    public int getArrangementId() {
        return this.arrangementId;
    }
    
    public void setArrangementId(int arrangementId) {
        this.arrangementId = arrangementId;
    }
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public String getBeskrivelse() {
        return this.beskrivelse;
    }
    
    public void setBeskrivelse(String beskrivelse) {
        this.beskrivelse = beskrivelse;
    }
    public String getDato() {
        return this.dato;
    }
    
    public void setDato(String dato) {
        this.dato = dato;
    }
    public Set getTilmeldings() {
        return this.tilmeldings;
    }
    
    public void setTilmeldings(Set tilmeldings) {
        this.tilmeldings = tilmeldings;
    }




}


