package Entity;
// Generated 21-09-2009 17:38:20 by Hibernate Tools 3.2.1.GA



/**
 * Adresse generated by hbm2java
 */
public class Adresse  implements java.io.Serializable {


     private Integer id;
     private Kunde kunde;
     private String vej;
     private String postnummer;
     private String city;


    public Adresse() {
    }

	
    public Adresse(Kunde kunde, String vej, String postnummer, String city) {
        this.kunde = kunde;
        this.vej = vej;
        this.postnummer = postnummer;
        this.city = city;
    }
   
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Kunde getKunde() {
        return this.kunde;
    }
    
    public void setKunde(Kunde kunde) {
        this.kunde = kunde;
    }
    public String getVej() {
        return this.vej;
    }
    
    public void setVej(String vej) {
        this.vej = vej;
    }
    public String getPostnummer() {
        return this.postnummer;
    }
    
    public void setPostnummer(String postnummer) {
        this.postnummer = postnummer;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

     public String toString(){
        return " adresseId: " + id + " vej: " + vej + " postnummer: " + postnummer + " by: " + city;
    }
   
}


