package Entity;
// Generated 21-09-2009 17:38:20 by Hibernate Tools 3.2.1.GA


/**
 * Kunde generated by hbm2java
 */
public class Kunde  implements java.io.Serializable {


     private Integer id;
     private Adresse adresse;
     private String navn;
     private String tlf;

    public Kunde() {
    }

	
    public Kunde(Adresse adresse, String navn, String tlf) {
        this.adresse = adresse;
        this.navn = navn;
        this.tlf = tlf;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }

    public String toString(){
        return " kundeID: " + id + " navn: " + navn + " tlf: " + tlf + " Adresse: " + adresse;
    }

}


